<?
$aMenuLinks = array(
    array(
        "Медицина",
        "/meditsina/",
        array(),
        array(),
        ""
    ),
    array(
        "Косметология",
        "/kosmetologiya/",
        array(),
        array(),
        ""
    ),
    array(
        "Оборудование",
        "/oborudovanie/",
        array(),
        array(),
        ""
    ),
    array(
        "Лаборатория",
        "/laboratoriya/",
        array(),
        array(),
        ""
    ),
    array(
        "Акции",
        "/aktsii/",
        array(),
        array(),
        ""
    ),
    array(
        "Специалисты",
        "/spetsialisty/",
        array(),
        array(),
        ""
    ),
    array(
        "О клинике",
        "/o-klinike/",
        array(),
        array(),
        ""
    ),
    array(
        "Контакты",
        "/kontakty/",
        array(),
        array(),
        ""
    )
);
